### ISSUE TITLE
[BUG] Server enters crash loop after adding ServerStats

### ISSUE THREAD

**Issue by obvionaoe** [diced/ServerStats#2]
**Describe the bug**
As soon as i added this to my Fabric server and restarted, the server entered a crash loop...

**To Reproduce**
1. run a Fabric server through the itzg/docker-minecraft-server image
2. add ServerStats to the mods folder
3. restart the server
4. see crash loop

**Expected behavior**
The server should not crash loop and work as normal

**Please complete the following information):**
 - OS: Ubuntu Server
 - Server Software: Fabric
 - ServerStats Version: 1.2.7

**Comment by diced** [comment]
Is there any error that happens once you run the server?

**Comment by obvionaoe** [comment]
Sorry for taking so long to reply, but I didn't have the time to mess with this again till now! I installed the newest version again 1.2.8 with carpet and everything worked as expected now! Thanks

**Comment by diced** [comment]
> Sorry for taking so long to reply, but I didn't have the time to mess with this again till now! I installed the newest version again 1.2.8 with carpet and everything worked as expected now! Thanks

No problem, glad to hear that the fix worked. It's mostly my fault for leaving a bunch of issues here for 4 months, I hope I get notifications after this lol.
