### ISSUE TITLE
[BUG] Stopping ServerStats-Worker

### ISSUE THREAD

**Issue by whes1015** [diced/ServerStats#6]
**Describe the bug**

**To Reproduce**
1. When stop server, Server always say Stopping ServerStats-Worker and server can't close

**Expected behavior**

**Screenshots**

**Please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS]
 - Server Software: [e.g. Bukkit, Paper, Spigot, Fabric, Bungee]
 - ServerStats Version: [e.g. 1.2.0]

**Additional context**

**Comment by diced** [comment]
You didn't complete the following information containing OS, Server Software and Server stats version. Please edit your issue or comment with those details filled out.

**Comment by whes1015** [comment]
> You didn't complete the following information containing OS, Server Software and Server stats version. Please edit your issue or comment with those details filled out.

I'm not sure how does the problem happened ,so I temporary close this issue
