### ISSUE TITLE
The documentation website cannot be opened

### ISSUE THREAD

**Issue by yurisasc** [diced/ServerStats#8]
**Describe the bug**
Seems like the docs website is down? Is it possible to access the docs from a readme file in the meantime?

**To Reproduce**
1. Go to serverstats.diced.me
2. You'll get a blank page and redirected to 1redirb.com

**Comment by superintendent2521** [comment]
Now the site is completely down. DNS error, so apparently it doesnt exist in The public revolver caches anymore.

**Comment by diced** [comment]
Sorry! it has been updated
